apiVersion: v1
kind: Service
metadata:
  name: {{ include "expertise-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "expertise-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "expertise-api.apiSelectorLabels" . | nindent 4 }}
